### ISSUE TITLE
Fix for mir test

### ISSUE THREAD

**Issue by filman230** [vanyasem/Lomiri-Arch#25]
I don't know if this is the best place for that, but I have a suggestion for the mir PKGBUILD (https://aur.archlinux.org/packages/mir/ and https://aur.archlinux.org/packages/mir/ )

The lines 
```
check() {
  cd ${pkgname}-${pkgver}/${BUILD_DIR}
  GTEST_OUTPUT=xml:./
  bin/mir_acceptance_tests
  bin/mir_integration_tests
  bin/mir_unit_tests
}
```
should be replaced by
```
check() {
  cd ${pkgname}-${pkgver}/${BUILD_DIR}
  GTEST_OUTPUT=xml:./
  make ptest
}
```
See https://github.com/MirServer/mir/issues/1603 for the reason.

**Comment by vanyasem** [comment]
https://aur.archlinux.org/cgit/aur.git/commit/?h=mir-git&id=8e1286b2d6e3ae029c1d9285abd9419f93316160
